modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/whirlfrenzy/custom-item-despawn-duration/issues"
license = "MIT"

[[mods]]
modId = "custom_item_despawn_duration"
version = "${version}"
displayName = "Custom Item Despawn Duration"
authors = "whirlfrenzy"
description = '''
Configure how long items will last before despawning
'''
#logoFile = ""

[[dependencies.custom_item_despawn_duration]]
modId = "forge"
mandatory = true
versionRange = "[47.0,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.custom_item_despawn_duration]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
