modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/whirlfrenzy/configurable-item-despawn-duration/issues"
license = "MIT"

[[mods]]
modId = "configurable_item_despawn_duration"
version = "${version}"
displayName = "Configurable Item Despawn Duration"
authors = "whirlfrenzy"
description = '''
Configure how long items will last before despawning
'''
#logoFile = ""

[[dependencies.custom-item-despawn-duration]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.custom-item-despawn-duration]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "configurable-item-despawn-duration.mixins.json"
