modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/whirlfrenzy/custom-item-despawn-duration/issues"
license = "MIT"

[[mods]]
modId = "custom_item_despawn_duration"
version = "${version}"
displayName = "Custom Item Despawn Duration"
authors = "whirlfrenzy"
description = '''
Configure how long items will last before despawning
'''
#logoFile = ""

[[dependencies.custom_item_despawn_duration]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.110-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.custom_item_despawn_duration]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "custom-item-despawn-duration.mixins.json"
